namespace CSDB_UtopiaModel.Persistence;
    abstract class Field {
        protected Resource resource;
        protected int depletionLevel;
        protected Town? town;
        protected Buildable? buildable;
        protected int mood;
        protected int _x;
        protected int _y;
        ;
        public int X;
        public int Y;
        public bool HasBuildable;
        public bool IsPartOfTown;
        public int MoodLevel;
        ;
        public void Field(int,int);
        public bool Place(Buyable);
        public bool Demolish();
    };
